export const AUDIT_ACTIONS = {
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  
  CLINIC_CREATED: 'CLINIC_CREATED',
  
  PATIENT_CREATED: 'PATIENT_CREATED',
  
  DOCTOR_CREATED: 'DOCTOR_CREATED',
  
  APPOINTMENT_CREATED: 'APPOINTMENT_CREATED',
  APPOINTMENT_UPDATED: 'APPOINTMENT_UPDATED',
  APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
  APPOINTMENT_COMPLETED: 'APPOINTMENT_COMPLETED',
  
  CONSULTATION_CREATED: 'CONSULTATION_CREATED',
  CONSULTATION_UPDATED: 'CONSULTATION_UPDATED',
  
  PRESCRIPTION_CREATED: 'PRESCRIPTION_CREATED',
  PRESCRIPTION_FINALIZED: 'PRESCRIPTION_FINALIZED',
  
  INVOICE_CREATED: 'INVOICE_CREATED',
  INVOICE_ISSUED: 'INVOICE_ISSUED',
  PAYMENT_RECORDED: 'PAYMENT_RECORDED',
};
