export const APPOINTMENT_STATUS = {
  SCHEDULED: 'SCHEDULED',
  CONFIRMED: 'CONFIRMED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW'
};
export const APPOINTMENT_STATUS_LIST = Object.values(APPOINTMENT_STATUS);

export const CONSULTATION_STATUS = {
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};
export const CONSULTATION_STATUS_LIST = Object.values(CONSULTATION_STATUS);

export const PRESCRIPTION_STATUS = {
  DRAFT: 'DRAFT',
  FINALIZED: 'FINALIZED'
};
export const PRESCRIPTION_STATUS_LIST = Object.values(PRESCRIPTION_STATUS);

export const INVOICE_STATUS = {
  DRAFT: 'DRAFT',
  ISSUED: 'ISSUED',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED'
};
export const INVOICE_STATUS_LIST = Object.values(INVOICE_STATUS);

export const PAYMENT_METHOD = {
  CASH: 'CASH',
  CARD: 'CARD',
  UPI: 'UPI',
  BANK_TRANSFER: 'BANK_TRANSFER',
  OTHER: 'OTHER'
};
export const PAYMENT_METHOD_LIST = Object.values(PAYMENT_METHOD);

export const PAYMENT_STATUS = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
};
export const PAYMENT_STATUS_LIST = Object.values(PAYMENT_STATUS);
