export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  CLINIC_ADMIN: 'CLINIC_ADMIN',
  DOCTOR: 'DOCTOR',
  RECEPTIONIST: 'RECEPTIONIST',
  STAFF: 'STAFF',
  PATIENT: 'PATIENT'
};

export const CLINIC_LEVEL_ROLES = [
  ROLES.CLINIC_ADMIN,
  ROLES.DOCTOR,
  ROLES.RECEPTIONIST,
  ROLES.STAFF,
  ROLES.PATIENT
];

export const ALL_ROLES = Object.values(ROLES);
